class AlreadyExistsError(Exception):
    pass

class ValidationError(Exception):
    pass